# Generated by Django 3.0.5 on 2020-04-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyName', models.CharField(max_length=200)),
                ('patientName', models.CharField(max_length=200)),
                ('isDone', models.BooleanField(default=False)),
                ('isProcessing', models.BooleanField(default=False)),
                ('isGoodData', models.BooleanField(default=True)),
                ('status', models.CharField(default='Not started', max_length=200)),
                ('dataToProc', models.FilePathField(blank=True)),
                ('data_loc', models.FilePathField(blank=True)),
                ('studyID', models.IntegerField()),
            ],
        ),
    ]
