# Generated by Django 3.0.5 on 2020-04-13 23:33

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dataToProc',
        ),
        migrations.RemoveField(
            model_name='task',
            name='data_loc',
        ),
        migrations.AddField(
            model_name='task',
            name='processedData',
            field=models.FilePathField(blank=True, path=task.models.processed_path),
        ),
        migrations.AddField(
            model_name='task',
            name='unprocessedData',
            field=models.FilePathField(blank=True, path=task.models.unprocessed_path),
        ),
    ]
