# Generated by Django 3.0.5 on 2020-04-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_task_isavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='recon_started',
            field=models.BooleanField(default=False),
        ),
    ]
