# Generated by Django 3.0.5 on 2020-04-11 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_auto_20200411_0408'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='isProcessing',
            field=models.BooleanField(default=False),
        ),
    ]
