# Generated by Django 3.0.5 on 2020-04-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_study_isprocessing'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyaccess',
            name='user',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
