# Generated by Django 3.0.5 on 2020-04-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0005_studyaccess_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
