# Generated by Django 3.0.5 on 2020-04-12 00:02

from django.db import migrations, models
import studies.models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0006_study_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='_id',
        ),
        migrations.AlterField(
            model_name='study',
            name='data_loc',
            field=models.FilePathField(blank=True, path=studies.models.studies_path),
        ),
        migrations.AlterField(
            model_name='study',
            name='pub_date',
            field=models.DateTimeField(),
        ),
    ]
