# Generated by Django 3.0.5 on 2020-04-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0007_auto_20200412_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='status',
            field=models.CharField(default='Not started', max_length=200),
        ),
    ]
