# Generated by Django 3.0.5 on 2020-04-10 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import studies.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('patient', models.CharField(max_length=25)),
                ('data_loc', models.FilePathField(path=studies.models.studies_path)),
                ('_id', models.CharField(max_length=200)),
                ('docs', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FilePathField(path='/home/michael/results/studies')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.Study')),
            ],
        ),
    ]
